const CartActionsTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM_CART: 'ADD_ITEM_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART', 
    DECREASE_ITEM: 'DECREASE_ITEM', 
}

export default CartActionsTypes;